version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      JWT_SECRET: ${JWT_SECRET}
      UKR_NET_MAIL: ${UKR_NET_MAIL}
      UKR_NET_PASSWORD: ${UKR_NET_PASSWORD}

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
