version: '3'
services:
  postgres_db:
    image: postgres:12
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build: .
    ports:
      - "3000:8000"
    networks:
      - app-network
    depends_on:
      - postgres_db

networks:
  app-network:
    name: app-network

volumes:
  postgres_data: